export const colors = {
  light: {
    primary: "#0f766e",
    primaryForeground: "#ffffff",
    background: "#ffffff",
    foreground: "#0f172a",
    card: "#ffffff",
    cardBorder: "#e2e8f0",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    inputBackground: "#ffffff",
    inputBorder: "#cbd5e1",
    success: "#22c55e",
    warning: "#f59e0b",
    amber: "#f59e0b",
  },
  dark: {
    primary: "#14b8a6",
    primaryForeground: "#ffffff",
    background: "#0f172a",
    foreground: "#f8fafc",
    card: "#1e293b",
    cardBorder: "#334155",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#334155",
    inputBackground: "#1e293b",
    inputBorder: "#475569",
    success: "#22c55e",
    warning: "#f59e0b",
    amber: "#f59e0b",
  },
};

export type ThemeColors = typeof colors.light;
